import { defineConfig } from "oxlint";
import core from "ultracite/oxlint/core";
import react from "ultracite/oxlint/react";

export default defineConfig({
  extends: [core, react],
  ignorePatterns: [...core.ignorePatterns, ".agents/**"],
  rules: {
    "arrow-body-style": "off",
    complexity: "off",
    curly: "off",
    eqeqeq: "off",
    "func-style": "off",
    "import/consistent-type-specifier-style": "off",
    "import/no-named-as-default-member": "off",
    "jsdoc/check-tag-names": "off",
    "jsx-a11y/click-events-have-key-events": "off",
    "jsx-a11y/label-has-associated-control": "off",
    "jsx-a11y/no-noninteractive-element-interactions": "off",
    "jsx-a11y/prefer-tag-over-role": "off",
    "no-empty-function": "off",
    "no-eq-null": "off",
    "no-await-in-loop": "off",
    "no-negated-condition": "off",
    "no-nested-ternary": "off",
    "no-shadow": "off",
    "no-unused-vars": "off",
    "no-use-before-define": "off",
    "oxc/no-barrel-file": "off",
    "react/react-compiler": "off",
    "react/jsx-no-constructed-context-values": "off",
    "react/no-unescaped-entities": "off",
    "react/no-unstable-nested-components": "off",
    "require-await": "off",
    "require-unicode-regexp": "off",
    "sort-keys": "off",
    "typescript/consistent-type-definitions": "off",
    "typescript/no-explicit-any": "off",
    "unicorn/consistent-function-scoping": "off",
    "unicorn/no-negated-condition": "off",
    "unicorn/no-nested-ternary": "off",
    "unicorn/prefer-export-from": "off",
    "unicorn/prefer-module": "off",
    "unicorn/prefer-spread": "off",
    "unicorn/require-module-specifiers": "off",
    "unicorn/text-encoding-identifier-case": "off",
  },
});
