import { describe, expect, it } from "vitest";

import type { AwsBlocksApi, DateRequestInput } from "./types";

describe("AWS Blocks API surface", () => {
  it("keeps the expanded API methods typed", () => {
    const methodNames: (keyof AwsBlocksApi)[] = [
      "acceptCircleInvite",
      "acceptVenueInvite",
      "approveVenueClaim",
      "captureVenueMenu",
      "createVenueIdentityVerificationSession",
      "getVenueIdentityVerificationStatus",
      "listVenueMenuItems",
      "upsertVenueMenuItem",
      "upsertVenueMenuModifierGroup",
      "upsertVenueMenuModifierOption",
      "checkIn",
      "completeDate",
      "createCircle",
      "createFriendInvite",
      "createMediaUpload",
      "generateAiResponse",
      "getAccountEntitlements",
      "getCircles",
      "getDateMedia",
      "getDateMeeting",
      "getDatingSummary",
      "createIdentityVerificationSession",
      "getIdentityVerificationStatus",
      "getUsernameChangeStatus",
      "listUsernameChangeRequests",
      "getFriendships",
      "getMediaUrl",
      "getMessages",
      "getNotifications",
      "getPendingReviews",
      "getPlacePhoto",
      "getPricingPlans",
      "getProfile",
      "getRecaps",
      "getReviewPrompt",
      "getRooms",
      "getVapidPublicKey",
      "getVenueLocations",
      "getVenueWorkspace",
      "getVenueAnalytics",
      "getVenueTimeline",
      "getVenuePublicSummary",
      "listPublicVenueSpecials",
      "listVenueSpecials",
      "createVenueSpecial",
      "updateVenueSpecial",
      "setVenuePublicAnalytics",
      "recordVenueOperationalEvent",
      "endVenueDiningSession",
      "listVenueTables",
      "upsertVenueTable",
      "createVenueLocation",
      "createVenueMediaUpload",
      "createVenueReferral",
      "followVenue",
      "previewVenueMenu",
      "requestVenueClaim",
      "requestVenueReservation",
      "requestVenueShiftSwap",
      "saveVenueMedia",
      "markChatRead",
      "markNotificationsRead",
      "publishRecap",
      "publishTyping",
      "requestFriendship",
      "requestUsernameChange",
      "verifyUsernameChange",
      "approveUsernameChange",
      "respondFriendship",
      "runDateLifecycle",
      "saveProfile",
      "saveProfileDraft",
      "savePushSubscription",
      "seedPricingPlans",
      "sendMessage",
      "sendPushNotification",
      "startDate",
      "startVenueDiningSession",
      "createVenueOrder",
      "submitReview",
      "subscribeNotifications",
      "subscribeVenueEvents",
      "suggestPlaces",
      "syncPricingPlans",
      "configureStripeConnect",
      "getStripeConnectStatus",
      "updateCircle",
      "updatePricingPlans",
      "updateVenueBrand",
      "updateVenueOrder",
      "updateVenueReservation",
      "uploadDateMedia",
      "inviteCircleMembers",
      "inviteVenueMembers",
    ];

    expect(methodNames).toHaveLength(94);
  });

  it("allows an optional direct friend target without changing normal requests", () => {
    const normalRequest: DateRequestInput = {
      filters: [],
      partyMembers: [],
      paymentMode: "dutch",
      places: [
        { name: "Good Company", placeId: "place-1", types: ["restaurant"] },
      ],
      scheduledAt: "2026-08-03T18:00:00.000Z",
      searchArea: "Little Rock",
      what: ["eat"],
    };
    const directRequest: DateRequestInput = {
      ...normalRequest,
      friendUserId: "friend-user-id",
    };

    expect(normalRequest.friendUserId).toBeUndefined();
    expect(directRequest.friendUserId).toBe("friend-user-id");
  });
});
